{
 "title": "MyApp",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MyApp Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "myapp_open_connections" }
   ]
  },
  {
   "title": "Thumbor Request duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(myapp_thumbor_request_duration_seconds_bucket{job=\"monitoring\"}[1m])) by (le))\n\n",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(myapp_thumbor_request_duration_seconds_bucket{job=\"monitoring\"}[1m])) by (le))\n\n",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(myapp_thumbor_request_duration_seconds_bucket{job=\"monitoring\"}[1m])) by (le))\n\n",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "MyApp Request duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(myapp_handlers_duration_seconds_bucket{job=\"monitoring\"}[1m])) by (le))\n\n",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(myapp_handlers_duration_seconds_bucket{job=\"monitoring\"}[1m])) by (le))\n\n",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(myapp_handlers_duration_seconds_bucket{job=\"monitoring\"}[1m])) by (le))\n\n",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Thumbor client requests / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(myapp_thumbor_requests_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "MyApp Request Duration by Path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(myapp_handlers_duration_seconds_count{job=\"monitoring\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Cached Images",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "myapp_redis_cached" }
   ]
  },
  {
   "title": "Redis Returned Cache",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "myapp_redis_returned_cache" }
   ]
  },
  {
   "title": "Redis Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(myapp_redis_request_duration_seconds_count{job=\"monitoring\"}[1m])"
    }
   ]
  }
 ]
}